# Generated by Django 5.2.18 on 2026-10-07 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(max_length=16)),
                ('source', models.CharField(choices=[('ONLINE', 'Online'), ('ON_SPOT', 'On-spot')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event')),
                ('ticket_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.tickettier')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event', 'created_at'], name='registratio_event_i_f44d95_idx'), models.Index(fields=['source', 'created_at'], name='registratio_source_dfb5ee_idx')],
            },
        ),
    ]
