# Generated by Django 5.2.18 on 2026-10-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='buyer_job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registration',
            name='buyer_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
