# Generated by Django 5.2.18 on 2026-10-08 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_buyer_job_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationIdempotency',
            fields=[
                ('key', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_record', to='registrations.registration')),
            ],
        ),
    ]
