# Generated by Django 5.2.18 on 2026-10-08 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_update_dhandiya_description'),
        ('registrations', '0003_registration_idempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['-created_at'], name='reg_created_at_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['buyer_email'], name='reg_buyer_email_idx'),
        ),
    ]
