# Generated by Django 5.2.18 on 2026-10-10 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_update_dhandiya_description'),
        ('registrations', '0005_registration_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('PENDING_VERIFICATION', 'Payment pending verification'), ('REJECTED', 'Payment proof rejected'), ('PAYMENT_VERIFIED', 'Payment verified'), ('TICKET_ISSUED', 'Ticket issued'), ('EXPIRED', 'Reservation expired'), ('CANCELLED', 'Cancelled')], default='TICKET_ISSUED', max_length=24),
        ),
        migrations.AddField(
            model_name='registration',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_reserved', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONSUMED', 'Consumed'), ('RELEASED', 'Released')], default='RESERVED', max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='events.event')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservation', to='registrations.registration')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'status', 'expires_at'], name='registratio_event_i_76048e_idx')],
            },
        ),
    ]
