# Generated by Django 5.2.18 on 2026-10-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_registration_status_registration_ticket_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketIdSequence',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
