# Generated by Django 5.2.18 on 2026-10-07 15:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='music', max_length=40)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('venue', models.CharField(max_length=240)),
                ('city', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('OPEN', 'Open'), ('SOLD_OUT', 'Sold out'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=16)),
                ('registration_open', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('schedule', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('accent_color', models.CharField(default='#b71959', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('start_at',),
                'indexes': [models.Index(fields=['status', 'registration_open'], name='events_even_status_4914b6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='event_end_after_start'), models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='event_capacity_positive')],
            },
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('admission_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(blank=True, max_length=300)),
                ('perks', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiers', to='events.event')),
            ],
            options={
                'ordering': ('price',),
                'constraints': [models.UniqueConstraint(fields=('event', 'slug'), name='unique_event_ticket_tier_slug'), models.CheckConstraint(condition=models.Q(('admission_count__gt', 0)), name='tier_admissions_positive'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='tier_price_nonnegative')],
            },
        ),
    ]
