# Generated by Django 5.2.18 on 2026-10-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='instructions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='reporting_time',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='rules_and_regulations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
