# Generated by Django 5.2.18 on 2026-10-07 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gates', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scanning.gate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('ENTRY_GRANTED', 'Entry granted'), ('ALREADY_USED', 'Already used'), ('INVALID_TICKET', 'Invalid ticket'), ('CANCELLED', 'Cancelled ticket'), ('WRONG_EVENT', 'Wrong event'), ('EVENT_CLOSED', 'Event closed')], max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='events.event')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='scanning.gate')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_scans', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_history', to='tickets.ticket')),
            ],
            options={
                'ordering': ('-scanned_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='gate',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_event_gate_name'),
        ),
        migrations.AddConstraint(
            model_name='staffassignment',
            constraint=models.UniqueConstraint(fields=('user', 'gate'), name='unique_user_gate_assignment'),
        ),
        migrations.AddIndex(
            model_name='ticketscan',
            index=models.Index(fields=['event', 'scanned_at'], name='scanning_ti_event_i_9313d5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketscan',
            index=models.Index(fields=['ticket', 'scanned_at'], name='scanning_ti_ticket__513ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketscan',
            index=models.Index(fields=['result', 'scanned_at'], name='scanning_ti_result_37d9b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketscan',
            constraint=models.UniqueConstraint(condition=models.Q(('result', 'ENTRY_GRANTED')), fields=('ticket',), name='ticket_has_at_most_one_granted_scan'),
        ),
    ]
