# Generated by Django 5.2.18 on 2026-10-08 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_update_dhandiya_description'),
        ('scanning', '0002_alter_ticketscan_ticket'),
        ('tickets', '0003_ticket_ticket_created_at_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticketscan',
            index=models.Index(fields=['-scanned_at'], name='scan_scanned_at_desc_idx'),
        ),
    ]
