# Generated by Django 5.2.18 on 2026-10-08 01:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registrations', '0003_registration_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('idempotency_key', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('request_hash', models.CharField(max_length=64)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(max_length=16)),
                ('buyer_organization', models.CharField(blank=True, max_length=200)),
                ('buyer_job_title', models.CharField(blank=True, max_length=120)),
                ('attendee_names', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='events.event')),
                ('registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intent', to='registrations.registration')),
                ('ticket_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='events.tickettier')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('CREATING', 'Creating order'), ('CREATED', 'Order created'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed')], default='CREATING', max_length=12)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentintent')),
            ],
        ),
        migrations.CreateModel(
            name='TicketDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=10)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_delivery', to='registrations.registration')),
            ],
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['event', 'status', 'expires_at'], name='payments_pa_event_i_3a67c0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['buyer_email', 'created_at'], name='payments_pa_buyer_e_76bd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['intent', 'status', 'created_at'], name='payments_pa_intent__d48186_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['verification_status', 'created_at'], name='payments_pa_verific_cae45b_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CAPTURED'), ('verification_status', 'VERIFIED')), fields=('intent',), name='one_verified_capture_per_payment_intent'),
        ),
        migrations.AddIndex(
            model_name='ticketdelivery',
            index=models.Index(fields=['status', 'updated_at'], name='payments_ti_status_1736a7_idx'),
        ),
    ]
