# Generated by Django 5.2.18 on 2026-10-08 02:15

import django.db.models.deletion
from django.db import migrations, models


def migrate_registration_deliveries_to_tickets(apps, schema_editor):
    Delivery = apps.get_model("payments", "TicketDelivery")
    database = schema_editor.connection.alias

    for delivery in Delivery.objects.using(database).select_related("registration").iterator():
        tickets = list(
            delivery.registration.tickets.using(database).order_by("created_at", "id")
        )
        if not tickets:
            delivery.delete(using=database)
            continue

        if delivery.status == "RETRYING":
            delivery.status = "PENDING"
        delivery.ticket_id = tickets[0].id
        delivery.save(
            using=database,
            update_fields=("ticket", "status"),
        )
        for ticket in tickets[1:]:
            Delivery.objects.using(database).create(
                registration=None,
                ticket_id=ticket.id,
                recipient=delivery.recipient,
                status=delivery.status,
                attempt_count=delivery.attempt_count,
                failure_reason=delivery.failure_reason,
                sent_at=delivery.sent_at,
                created_at=delivery.created_at,
                updated_at=delivery.updated_at,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('tickets', '0002_ticket_attendee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDailyUsage',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('regular_sent', models.PositiveSmallIntegerField(default=0)),
                ('priority_sent', models.PositiveSmallIntegerField(default=0)),
                ('regular_slots_used', models.PositiveSmallIntegerField(default=0)),
                ('priority_slots_used', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='ticketdelivery',
            name='payments_ti_status_1736a7_idx',
        ),
        migrations.RenameField(
            model_name='ticketdelivery',
            old_name='last_error',
            new_name='failure_reason',
        ),
        migrations.AddField(
            model_name='ticketdelivery',
            name='claim_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketdelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketdelivery',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketdelivery',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketdelivery',
            name='pdf_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketdelivery',
            name='priority',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('COMPLIMENTARY', 'Complimentary'), ('REGULAR', 'Regular')], default='REGULAR', max_length=16),
        ),
        migrations.AddField(
            model_name='ticketdelivery',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticketdelivery',
            name='quota_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketdelivery',
            name='quota_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketdelivery',
            name='retry_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketdelivery',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_delivery', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketdelivery',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_delivery', to='registrations.registration'),
        ),
        migrations.RunPython(
            migrate_registration_deliveries_to_tickets,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='ticketdelivery',
            name='registration',
        ),
        migrations.AlterField(
            model_name='ticketdelivery',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='email_delivery', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketdelivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=12),
        ),
        migrations.AddIndex(
            model_name='ticketdelivery',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='payments_ti_status_c6721a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketdelivery',
            index=models.Index(fields=['retry_after', 'status'], name='payments_ti_retry_a_ae9cc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='emaildailyusage',
            constraint=models.CheckConstraint(condition=models.Q(('regular_slots_used__lte', 295)), name='email_daily_regular_quota_limit'),
        ),
        migrations.AddConstraint(
            model_name='emaildailyusage',
            constraint=models.CheckConstraint(condition=models.Q(('priority_slots_used__lte', 5)), name='email_daily_priority_quota_limit'),
        ),
        migrations.AddConstraint(
            model_name='emaildailyusage',
            constraint=models.CheckConstraint(condition=models.Q(('regular_sent__lte', models.F('regular_slots_used')), ('priority_sent__lte', models.F('priority_slots_used'))), name='email_daily_sent_within_reserved'),
        ),
    ]
