# Generated by Django 5.2.18 on 2026-10-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_emaildailyusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket_issuance_failure',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='payment',
            name='ticket_issuance_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Tickets issued'), ('ADMIN_REVIEW_REQUIRED', 'Admin review required')], default='PENDING', max_length=24),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('REVIEW_REQUIRED', 'Payment review required')], default='PENDING', max_length=24),
        ),
    ]
