# Generated by Django 5.2.18 on 2026-10-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_ticket_issuance_failure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
