# Generated by Django 5.2.18 on 2026-10-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_captured_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdelivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RECONCILIATION_REQUIRED', 'Reconciliation required')], default='PENDING', max_length=24),
        ),
    ]
