# Generated by Django 5.2.18 on 2026-10-10 02:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payu_gateway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_verification_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='next_verification_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PaymentVerificationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('CALLBACK', 'PayU callback'), ('CLIENT', 'Browser status check'), ('ADMIN', 'Administrator retry'), ('SCHEDULED', 'Scheduled reconciliation')], max_length=12)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('environment', models.CharField(max_length=12)),
                ('outcome', models.CharField(choices=[('STARTED', 'Started'), ('CAPTURED', 'Captured'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('MISMATCH', 'Transaction mismatch'), ('AUTH_ERROR', 'Authentication error'), ('INVALID_REQUEST', 'Invalid API request'), ('TRANSACTION_NOT_FOUND', 'Transaction not found'), ('API_ERROR', 'API error'), ('MALFORMED', 'Malformed response'), ('NETWORK_ERROR', 'Network error')], default='STARTED', max_length=24)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('api_status', models.CharField(blank=True, max_length=24)),
                ('api_message', models.CharField(blank=True, max_length=300)),
                ('response_schema_valid', models.BooleanField(blank=True, null=True)),
                ('transaction_found', models.BooleanField(blank=True, null=True)),
                ('returned_txnid', models.CharField(blank=True, max_length=64)),
                ('returned_status', models.CharField(blank=True, max_length=40)),
                ('returned_unmappedstatus', models.CharField(blank=True, max_length=40)),
                ('returned_amount', models.CharField(blank=True, max_length=40)),
                ('expected_amount', models.PositiveIntegerField()),
                ('transaction_id_matches', models.BooleanField(blank=True, null=True)),
                ('amount_matches', models.BooleanField(blank=True, null=True)),
                ('booking_fields_match', models.BooleanField(blank=True, null=True)),
                ('currency_matches', models.BooleanField(blank=True, null=True)),
                ('retry_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_attempts', to='payments.payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_verification_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['payment', 'created_at'], name='payments_pa_payment_d7f663_idx')],
            },
        ),
    ]
