# Generated by Django 5.2.18 on 2026-10-10 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_proof_access_tokens(apps, schema_editor):
    PaymentIntent = apps.get_model("payments", "PaymentIntent")
    database = schema_editor.connection.alias
    intent_ids = list(
        PaymentIntent.objects.using(database)
        .filter(proof_access_token__isnull=True)
        .values_list("pk", flat=True)
    )
    for intent_id in intent_ids:
        PaymentIntent.objects.using(database).filter(pk=intent_id).update(
            proof_access_token=uuid.uuid4()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_last_verification_attempt_at_and_more'),
        ('registrations', '0006_registration_status_registration_ticket_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProofDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVED', 'Payment proof approved'), ('REJECTED', 'Payment proof rejected'), ('RESUBMITTED', 'Payment proof resubmitted'), ('RESERVATION_RELEASED', 'Inventory reservation released'), ('TICKET_ISSUED', 'Admission ticket issued')], max_length=24)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_content_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_screenshot',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_manual_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_email_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='payment',
            name='submission_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='utr_reference',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_manual_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='proof_access_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(
            populate_proof_access_tokens,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='proof_access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay (legacy)'), ('PAYU', 'PayU'), ('UPI_MANUAL', 'Manual UPI verification')], default='RAZORPAY', max_length=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATING', 'Creating order'), ('CREATED', 'Order created'), ('PENDING', 'Pending'), ('PENDING_VERIFICATION', 'Pending verification'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='CREATING', max_length=24),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider', 'UPI_MANUAL'), models.Q(('utr_reference', ''), _negated=True)), fields=('utr_reference',), name='unique_manual_payment_utr'),
        ),
        migrations.AddField(
            model_name='paymentproofdecision',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proof_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentproofdecision',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proof_decisions', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentproofdecision',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_decisions', to='registrations.registration'),
        ),
        migrations.AddIndex(
            model_name='paymentproofdecision',
            index=models.Index(fields=['registration', 'created_at'], name='payments_pa_registr_830294_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentproofdecision',
            index=models.Index(fields=['action', 'created_at'], name='payments_pa_action_4986c3_idx'),
        ),
    ]
