# Generated by Django 5.2.18 on 2026-10-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymentproofdecision_payment_proof_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_cloudinary_asset_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_cloudinary_version',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_format',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
