# Generated by Django 5.2.18 on 2026-10-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_proof_cloudinary_asset_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='proof_original_name',
        ),
    ]
