# Generated by Django 5.2.18 on 2026-10-10 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_payment_proof_original_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider', 'UPI_MANUAL'), models.Q(('transaction_id', ''), _negated=True)), fields=('transaction_id',), name='unique_manual_payment_txn_id'),
        ),
    ]
