# Generated by Django 5.2.18 on 2026-10-07 15:35

import apps.tickets.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=apps.tickets.models.create_ticket_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('USED', 'Used'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='registrations.registration')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['registration', 'status'], name='tickets_tic_registr_d16f4b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('status', 'ISSUED'), ('used_at__isnull', True)), models.Q(('cancelled_at__isnull', True), ('status', 'USED'), ('used_at__isnull', False)), models.Q(('cancelled_at__isnull', False), ('status', 'CANCELLED'), ('used_at__isnull', True)), _connector='OR'), name='ticket_status_timestamp_consistent')],
            },
        ),
    ]
