# Generated by Django 5.2.18 on 2026-10-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attendee_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
