# Generated by Django 5.2.18 on 2026-10-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_registration_reg_created_at_desc_idx_and_more'),
        ('tickets', '0002_ticket_attendee_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='ticket_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'created_at'], name='ticket_status_created_idx'),
        ),
    ]
